- project:
    name: theopenlab/envoy
    check:
      jobs:
        - envoy-build-arm64-test

- job:
    name: envoy-build-arm64-test
    parent: init-test
    description: |
      Envoy build in openlab cluster.
    run: .zuul/playbooks/envoy-build/run.yaml
    nodeset: ubuntu-xenial-arm64
